// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYb0sRcr2gGInP3fFV0_qqQMXun6EkFqI',
    appId: '1:997667523753:web:135d9f9233bdbd3f93adb8',
    messagingSenderId: '997667523753',
    projectId: 'robotic-heaven-438406-e7',
    authDomain: 'robotic-heaven-438406-e7.firebaseapp.com',
    storageBucket: 'robotic-heaven-438406-e7.firebasestorage.app',
    measurementId: 'G-HTD22HX540',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RaiI0YBSsN5y_oza2yyUOwWnzGTyQAw',
    appId: '1:997667523753:android:0fa6bf52ef5facc993adb8',
    messagingSenderId: '997667523753',
    projectId: 'robotic-heaven-438406-e7',
    storageBucket: 'robotic-heaven-438406-e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa62DqYI8X_TWLofgzZ5rBG5SaG2kE0cE',
    appId: '1:997667523753:ios:673b7a0d9d56c70893adb8',
    messagingSenderId: '997667523753',
    projectId: 'robotic-heaven-438406-e7',
    storageBucket: 'robotic-heaven-438406-e7.firebasestorage.app',
    iosBundleId: 'com.example.tubesPapb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa62DqYI8X_TWLofgzZ5rBG5SaG2kE0cE',
    appId: '1:997667523753:ios:673b7a0d9d56c70893adb8',
    messagingSenderId: '997667523753',
    projectId: 'robotic-heaven-438406-e7',
    storageBucket: 'robotic-heaven-438406-e7.firebasestorage.app',
    iosBundleId: 'com.example.tubesPapb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYb0sRcr2gGInP3fFV0_qqQMXun6EkFqI',
    appId: '1:997667523753:web:08f3d38ca7d204e393adb8',
    messagingSenderId: '997667523753',
    projectId: 'robotic-heaven-438406-e7',
    authDomain: 'robotic-heaven-438406-e7.firebaseapp.com',
    storageBucket: 'robotic-heaven-438406-e7.firebasestorage.app',
    measurementId: 'G-3ZJ7ESXF9S',
  );
}
